### ISSUE TITLE
Floating Point Imprecision causes incorrect behaviour in _advanceTraverse

### ISSUE THREAD

**Issue by crispycookies** [coatyio/vda-5050-lib.js#26]
**Describe the bug**
We wrote a simulator for VDA-AGVs to test our fleetmanager.

While simulating an AGV, we discovered that we might never reach a location because we "miss" it by a fraction of a `mm`.
For that reason, the simulated AGV continued driving well beyond the last base node. 

The cause was a IEEE754 rounding error:   
In our specific case, we expected `tx`, `dx` in  `_advanceTraverse` in `virtual-agv-adapter.ts` to be `0.0`, however, due to a rounding error `tx` was somewhere in the range of 10<sup>-16</sup> and `dx` was 10<sup>-17</sup>. For that reason, ,the condition `if (Math.abs(tx) <= Math.abs(dx) && Math.abs(ty) <= Math.abs(dy))` never fired, as `tx` was slightly larger than `dx`. This caused the simulated AGV to "never reach" the desired node and the simulated AGV position kept increasing well beyond the desired nodes position.

![image](https://user-images.githubusercontent.com/22690684/218082287-1c22f60a-6820-46b7-bc35-309a04817a5f.png)

**To Reproduce**
Make an AGV go from `NodeA` to `NodeB` via an Edge that goes straight from NodeA to `NodeB`:
````
NodeA: {x: -2mm, y: +4474mm}
NodeB: {x: -2mm, y: +248mm}
````
Obviously, the problem did not always happen when traversing the Edge from `NodeA` to `NodeB`, as it is highly dependend on how large of a time `realInterval` is. In our case, we used `tickRate = 5`, which translates to ~`200`. When changing the `tickRate` it may have worked better or worse, however we traced to underlying problem to a floating point rounding error, not a timing error.

For further information (including the exact project it was tested with), contact tobias.egger (at) siemens.com

**Expected behavior**
The simulated AGV should not miss the VDA node due to a floating point rounding error.

**Your Environment (please complete the following information):**
- Package Version: 1.3.0
- Node.js Version: v17.3.1
- OS: Windows 10

**Comment by ffa500** [comment]
Fixed in v1.2.0
