### ISSUE TITLE
Rename "AllowedDeviationXy" to "AllowedDeviationXY"

### ISSUE THREAD

**Issue by joachimfeld** [coatyio/vda-5050-lib.js#28]
**Describe the bug**
Rename "AllowedDeviationXy" to "AllowedDeviationXY"

**Is this a regression?**
In schema it was alway "AllowedDeviationXy" and in the written spec it was "AllowedDeviationXY"

Decision taken to leave it as "AllowedDeviationXY" also in schema

**Comment by ffa500** [comment]
My library implementation follows the "JSON schema is the single source of truth" principle as specified in VDA 5050 v1.1.0 PDF. As long as all the open and unclarified inconsistencies between spec and schema are not corrected by the VDA 5050 consortium, I will keep my library "as is" to avoid breaking changes for existing users.
