### ISSUE TITLE
updateError function of class AgvController removes all errors except the one that should be removed.

### ISSUE THREAD

**Issue by SoniSosony** [coatyio/vda-5050-lib.js#29]
Hi,

When you try remove an error using updateError function of class AgvController all errors are removed except the one that should be removed.

I think problem is in the function updateError. You are doing `newErrors = [...this._currentState.errors].splice(index, 1)`. Array.prototype.splice() returning an array containing the deleted elements. Then you update state using newErrors variable: `this._updateState(this._cloneState({ errors: newErrors }), reportImmediately)`

**Comment by ffa500** [comment]
Thanks for your bug report! This issue has been fixed in the new npm version 1.3.1 of the library.

**Comment by SoniSosony** [comment]
Thanks for the quick fix, cool library
