### ISSUE TITLE
Compatible with VDA5050 version 2.0.0

### ISSUE THREAD

**Issue by Hardold** [coatyio/vda-5050-lib.js#30]
Compatible with VDA5050 version 2.0.0, is there a plan?
https://github.com/VDA5050/VDA5050/tree/2.0.0

**Comment by hewu94** [comment]
Yes, we have just upgraded our lib to support both versions VDA5050 V1.1 and V2.0. 
Just use the latest library version 1.4.0 and specify the new clientOption `vdaVersion: "2.0.0"`
