### ISSUE TITLE
order validation fails to catch error when edge has end node not released

### ISSUE THREAD

**Issue by SoniSosony** [coatyio/vda-5050-lib.js#34]
Hi,

**Describe the bug**
After sending the task (example below), the AgvController will call the traverseEdge function defined in AgvAdapter. If I then call context.edgeTraversed() , it doesn't remove the edge from the EdgeState (just nothing happens). In VDA5050 v2.0.0, an edge can only be released when both the start and end nodes of the edge are released. I don't know if this is also the case in version 1.1.0.

`{
    "orderId": "order0001",
    "orderUpdateId": 0,
    "nodes": [
        {
            "nodeId": "N1",
            "sequenceId": 0,
            "released": true,
            "nodePosition": {
                "x": 0,
                "y": 0,
                "theta": 3.14,
                "mapId": "map",
                "allowedDeviationXY": 5
            },
            "actions": []
        },
        {
            "nodeId": "N2",
            "sequenceId": 2,
            "released": false,
            "nodePosition": {
                "x": 0,
                "y": 5,
                "theta": 3.14,
                "mapId": "map",
                "allowedDeviationXy": 2
            },
            "actions": []
        }
    ],
    "edges": [
        {
            "edgeId": "1",
            "sequenceId": 1,
            "released": true,
            "startNodeId": "N1",
            "endNodeId": "N2",
            "actions": []
        }
    ],
    "timestamp": "2023-03-07T15:15:05.395Z",
    "headerId": 0,
    "manufacturer": "Test",
    "serialNumber": "001",
    "version": "1.1.0"
}
`

**Expected behavior**
Order validation must fail

**Your Environment (please complete the following information):**
- Package Version: 1.3.1
- Node.js Version: 18.17.1
- OS: Ubuntu 20.04

**Comment by hewu94** [comment]
Thank you for bug report. 
The new library version 1.4.0 fixes this issue and also support VDA 5050 V2.0.
