### ISSUE TITLE
Naming issue in V2.0.0

### ISSUE THREAD

**Issue by MateuszOsuchVersabox** [coatyio/vda-5050-lib.js#35]
Hello,

I've noticed an issue while using version 1.4.0 with vdaVersion: "2.0.0". The name in the Interface InstantActions has not been updated from v.1.1.0.

Should be: instantActions [action] -> actions [action]

For reference, check the vda5050 documentation, chapter [6.9.](https://github.com/VDA5050/VDA5050/blob/2.0.0/VDA5050_EN_V1.md#-69-topic-instantactions-from-master-to-control-to-agv)

**Comment by hewu94** [comment]
Fix in v1.4.2 
see  65a2334086913b3d054f1b47e42b2a29d81dc96f
